### ISSUE TITLE
Problems with .LocationAlways .LocationWhenInUse .Notifications

### ISSUE THREAD

**Issue by ghost** [delba/Permission#1]
Using .LocationAlways I get:
WARNING: NSLocationAlwaysUsageDescription not found in Info.plist

Using .LocationWhenInUse I get:
WARNING: NSLocationWhenInUseUsageDescription not found in Info.plist

I am unsure how to .Notifications correctly?

Thanks very handy!

**Comment by delba** [comment]
Add the corresponding keys in the Info.plist.

Initialize the Notification permission with a set of UIUserNotificationCategory.

**Comment by ghost** [comment]
thanks
