### ISSUE TITLE
Xcode 8.3: Argument type 'String' does not conform to expected type 'Any'

### ISSUE THREAD

**Issue by wgrand** [delba/Permission#102]
On Xcode 8.3, permissions return `Argument type 'String' does not conform to expected type 'Any'`

**Comment by delba** [comment]
Could you provide some context please?

**Comment by wgrand** [comment]
I think that the latest version fixes this, actually. I will verify and get back to you.

**Comment by delba** [comment]
Is it related to https://github.com/delba/Permission/pull/101 ?

**Comment by wgrand** [comment]
Yes, I'm pretty sure that's the issue.

**Comment by wgrand** [comment]
Okay, verified. 2.0.4 fixes this issue. Sorry for any confusion!

**Comment by zazoomauro** [comment]
I have the same issue here
Xcode Version 8.3.1 (8E1000a)

Error:
```
/xxx/App/Pods/Permission/Source/PermissionTypes/Camera.swift:41:19: Argument type 'String' does not conform to expected type 'Any'
```

Permission installed by `Podfile`
```
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'App' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for App
  pod 'Permission/Camera'
  pod 'Permission/Notifications'
end
```

and then

```
pod install
```
