### ISSUE TITLE
[Gem] Cocoapods breaks with latest xcodeproj gem.

### ISSUE THREAD

**Issue by hernangonzalez** [delba/Permission#104]
Hi,

I had to force:
`gem 'xcodeproj', '1.4.2'`

Version *1.4.3* seems to break the pod configuration.

Thanks,
H.

**Comment by mrgrauel** [comment]
I opened an issue in the corresponding repository https://github.com/CocoaPods/Xcodeproj/issues/478

It's not a fault by @delba it's a bug in `xcodeproj`

**Comment by delba** [comment]
Fixed by https://github.com/CocoaPods/CocoaPods/pull/6629
