### ISSUE TITLE
Unable to access Photos permission

### ISSUE THREAD

**Issue by theblixguy** [delba/Permission#105]
## Podfile:

* `pod 'Permission/Photos'`

## Code:

* `let permission: Permission = .photos`

## Error:

* `Type 'Permission' has no member 'photos'`

## More info:

* Xcode 8.3.1
* Swift 3.1
* iOS 10.3.2

**Comment by ahartwel** [comment]
This started happening to me when I updated cocoapods. I am not sure why, but the swift active compilation conditions are only being set for release builds now, not for debug.
If you replace "SWIFT_ACTIVE_COMPILATION_CONDITIONS" with "OTHER_SWIFT_FLAGS" in the podspec and add a "-D" before the value it will build properly.


the current podspec:
```
s.subspec 'Photos' do |ph|
    ph.dependency 'Permission/Core'
    ph.pod_target_xcconfig = { "SWIFT_ACTIVE_COMPILATION_CONDITIONS"  => "PERMISSION_PHOTOS" }
  end
```

what builds properly:
```
s.subspec 'Photos' do |ph|
    ph.dependency 'Permission/Core'
    ph.pod_target_xcconfig = { "OTHER_SWIFT_FLAGS"  => "-DPERMISSION_PHOTOS" }
  end
```

full podspec:
https://github.com/swarmnyc/Permission/blob/feature/custom_alert_controller/Permission.podspec

**Comment by ahartwel** [comment]
Here is a discussion about the issue https://github.com/CocoaPods/CocoaPods/issues/6625

**Comment by EstebanVallejo** [comment]
+1 This is happening to me too, with any permission ...

**Comment by leoneparise** [comment]
I solved this issue as @ahartwel commented. Here is my podspec:

https://github.com/leoneparise/Permission/blob/master/Permission.podspec

use my repo until they solve the cocoapods issue. Add 

`:git => 'https://github.com/leoneparise/Permission', :branch => 'master'`

 to each Permission entry in you podfile.

**Comment by EstebanVallejo** [comment]
@leoneparise Excellent! It worked, I'll use your fork until they fix the original one ;).

**Comment by bohachevskyy** [comment]
Thank you @leoneparise works like a charm!

**Comment by z-br** [comment]
None of the workarounds work for me. I've deleted Pods folder, tried the repo from @leoneparise , tried the workaround from @groue in the other thread - nothing works. Still get some error - I'm flummoxed!

**Comment by AnnieNinaJoyceV** [comment]
Using **leoneparise** podspec fixed the issue.
Any chance this will be pushed to `master` soon?

And, I have a query. If anyone can please clarify 🤔 

pod 'Permission/Camera'

Doesn't it mean, it will only download the files related to Camera permission and ignore all others?
I see it's downloading all the files.

**Comment by jrmsklar** [comment]
Using @leoneparise worked for me aw well!

@delba any ideas when this will be updated in [master](https://github.com/delba/Permission)?

**Comment by jrmsklar** [comment]
Using @leoneparise's fork worked for me as well!

@delba any ideas when this will be updated in [master](https://github.com/delba/Permission)?

**Comment by leoneparise** [comment]
@jrmsklar I don't know if it will be merged into master. This is a temporary fix until Cocoapods fix their code.

**Comment by oferRounds** [comment]
@gregpassmore - did you manage to solve your issue? For me also - none of the above solved it.

**Comment by oferRounds** [comment]
I also tried to include Permission without CocoaPods, still same issue...

**Comment by gghangura** [comment]
I am having the same issue. i tried adding everything mentioned here. Can some one help me please?

**Type 'Permission' has no member 'Camera'**

![image](https://user-images.githubusercontent.com/22323643/27494320-59c157a4-581b-11e7-8145-18a542067616.png)

![image](https://user-images.githubusercontent.com/22323643/27494329-615e2d0c-581b-11e7-8dcf-a944ed5596c7.png)

**Comment by ghost** [comment]
It's fixed in Cocoapods 1.3.1, update your version 🚀

**Comment by anirudhamahale** [comment]
I also had the same issue, so just update your CocoaPods framework.
You can update the framework by running `sudo gem install cocoapods` in terminal.

Hope this helps.

**Comment by delba** [comment]
Fixed with the latest `cocoapods` version. Closing it
