### ISSUE TITLE
Type 'Permission' has no member 'notifications'

### ISSUE THREAD

**Issue by tamoyal** [delba/Permission#106]
I have the latest Permission lib `2.0.4` and am getting an error with this line of code:
`let permission: Permission = .notifications(types: userNotificationTypes, categories: nil)
`
`Type 'Permission' has no member 'notifications'`

But I am not getting an error with this line:

`let permission: Permission = .contacts`
 so it seems to be properly installed

My podfile looks like:

```
  pod 'Permission/Contacts'
  pod 'Permission/Notifications'
  pod 'Permission/Location'
```

**Comment by gravicle** [comment]
Having the same issue in Xcode 8.3.2 as well as 8.3.1. Quite urgent as I cannot ship without a fix.

**Comment by gravicle** [comment]
@tamoyal Seems like a Cocopods and Xcode issue. https://github.com/delba/Permission/issues/105

**Comment by tamoyal** [comment]
@gravicle ufff issue title wasn't so revealing, will close this duplicate

**Comment by oferRounds** [comment]
@tamoyal where you able to solve this issue? Tried all suggestions, but nothing works :(
