### ISSUE TITLE
Facing a compiler error: 'Permission' is ambiguous for type lookup in this context

### ISSUE THREAD

**Issue by pranjaltech** [delba/Permission#107]
I'm using `Facebook Core` and `Permission` in the same file. 

```swift
import Permission
import FacebookCore
```
Later, I try using this: 

```swift
func registerForPushNotification() {
        let permission: Permission = .notifications
        // ...
}
```
This throws an error: 
![image](https://cloud.githubusercontent.com/assets/71014/25377460/4453910e-29c5-11e7-9968-272bf48b6550.png)

----
How do I solve this? 

I'm using XCode 8.3.2 with Swift.

**Comment by delba** [comment]
Try:

```swift
let permission: Permission.Permission = .notifications
```

**Comment by pasevin** [comment]
```let permission: Permission.Permission = .notifications``` doesn't help
