### ISSUE TITLE
Unable to access any Permission

### ISSUE THREAD

**Issue by gghangura** [delba/Permission#111]
I am having the same issue. i tried adding everything mentioned here. Can some one help me please?

**Type 'Permission' has no member 'Camera'**

![image](https://user-images.githubusercontent.com/22323643/27494320-59c157a4-581b-11e7-8145-18a542067616.png)

![image](https://user-images.githubusercontent.com/22323643/27494329-615e2d0c-581b-11e7-8dcf-a944ed5596c7.png)

**Comment by BANG88** [comment]
Please see https://github.com/delba/Permission/issues/105#issuecomment-294510265

**Comment by gghangura** [comment]
@bang88 none of the solutions worked for me.

**Comment by saruvij** [comment]
[This](https://github.com/delba/Permission/issues/113) one works, ji 😎

**Comment by gghangura** [comment]
I tried that too, does not work @saruvij

**Comment by hellensoloviy** [comment]
Why are you wrote ".Camera"? it should be all in lowercase.

**Comment by delba** [comment]
Hi @gghangura, the lib has been updated to the latest Swift version. Please contact me back if the issue persists.
