### ISSUE TITLE
Manual Integration Issues

### ISSUE THREAD

**Issue by saruvij** [delba/Permission#112]
Is there any link to refer to integrate the lib manually?

Am facing a lot of issues in the manual approach.

**Comment by saruvij** [comment]
Screenshot: 
<img width="881" alt="manual integration issue" src="https://user-images.githubusercontent.com/28537651/27863691-f6d75b42-61a8-11e7-805f-713248aa790e.png">

If I import UIKit, it raises other set of issues with the dictionaries declared below it, without using Hashable types.

**Comment by delba** [comment]
Hi @saruvij, `UIControl.State` doesn't comply by default to `Hashable` this is why you had the issues with the `[UIControl.State: Any]` dictionaries.

The conformance has been declared in another file (`Utilities.swift`). You might want to include this one as well if you want to use the lib manually.
