### ISSUE TITLE
Fails to build when using Swift 4

### ISSUE THREAD

**Issue by CraigSiemens** [delba/Permission#116]
The specific error I'm getting is:

```
Permission/Source/PermissionTypes/Camera.swift:30:57: Incorrect argument label in call (have 'forMediaType:', expected 'for:')
```

Looks like a method signature changed when using Swift 4. I'm only using `Camera` and `Location` so there may be other places that need to be updated.

**Comment by cjmconie** [comment]
Yes, Swift 4 does not compile (API signature changes)
However, if the Swift language versions is set as Swift 3.2 the module compiles without error. 

Is there a planned Swift 4 migration?

**Comment by rsaarloos** [comment]
#120

**Comment by delba** [comment]
Hi @CraigSiemens, the project has been updated to the latest Swift version
