### ISSUE TITLE
New permissions for keyboard extensions

### ISSUE THREAD

**Issue by bbqsrc** [delba/Permission#117]
Hey!

The [What's New for iOS 11](https://developer.apple.com/library/content/releasenotes/General/WhatsNewIniOS/Articles/iOS_11_0.html) states the following for keyboard extensions:

> Added new system permissions in Settings for app access to included Keyboard Extensions.

When the API becomes obvious, it would be great to have this added to this project.

**Comment by delba** [comment]
Hi @bbqsrc, thank you for the suggestion but the permission for custom keyboards (`Allow Full Access`) doesn't quite work the same way as the other permissions and should be left to the developper.
