### ISSUE TITLE
Push Notification permissions: how to get deviceToken?

### ISSUE THREAD

**Issue by agordeev** [delba/Permission#123]
`didRegisterForRemoteNotificationsWithDeviceToken` is never called.

**Comment by Evyasafmordechai** [comment]
Call to UIApplication.shared.registerForRemoteNotifications() when status is .authorized 

Duplicate issue: https://github.com/delba/Permission/issues/26

**Comment by delba** [comment]
Duplicate issue: #26 - Closing it
