### ISSUE TITLE
"Permission" is ambiguous for type lookup in this context in Swift

### ISSUE THREAD

**Issue by perlasivakrishna** [delba/Permission#126]
Hello 
 Im using Realm and Permission inn my project. Im getting errors. Please have a look at [this](https://stackoverflow.com/questions/50289440/class-is-ambiguous-for-type-lookup-in-this-context-in-swift?noredirect=1#comment87662554_50289440).

Thanks.

**Comment by delba** [comment]
Hi @perlasivakrishna, please use the latest versions of `Permission` (recently updated).
If the issue persists, did you try to namespace the class names ? (e.g. `Permission.Permission`)
