### ISSUE TITLE
Has this repo been abandoned?

### ISSUE THREAD

**Issue by CraigSiemens** [delba/Permission#131]
It's been a while since there have been any updates to this repo and there are many issues and PRs that have gone unanswered. Is there any future for this repo going forward or should we look at moving onto other forks or libraries?

I've been forced to use a fork of this repo because there haven't been updates here.
https://github.com/Dschee/Permission

**Comment by delba** [comment]
Hi @CraigSiemens, the project has been updated to Swift 5.1
