### ISSUE TITLE
Won't compile on Swift 4.2

### ISSUE THREAD

**Issue by johnharutyunyan** [delba/Permission#133]
Please can you make some changes?

**Comment by evdeve** [comment]
@johnharutyunyan There is descision for you:
`pod 'Permission', :git => 'https://github.com/evdeve/Permission'`

**Comment by johnharutyunyan** [comment]
@evdeve , thank you!!!

**Comment by hytaoist** [comment]
> @johnharutyunyan There is descision for you:
> `pod 'Permission', :git => 'https://github.com/evdeve/Permission'`

when i use it in a empty project, and pod install correctly, it occur a error call "Function with uninhabited return type 'PermissionType' is missing call to another never-returning function on all paths" in `Permission.swift` line: 136. `public let type: PermissionType`.  ??? how can i fix? or any problem in my operation?

**Comment by Ale111** [comment]
> > @johnharutyunyan There is descision for you:
> > `pod 'Permission', :git => 'https://github.com/evdeve/Permission'`
> 
> when i use it in a empty project, and pod install correctly, it occur a error call "Function with uninhabited return type 'PermissionType' is missing call to another never-returning function on all paths" in `Permission.swift` line: 136. `public let type: PermissionType`. ??? how can i fix? or any problem in my operation?

Hi, have you found a solution to fix this issue?
Thanks.
Ale

**Comment by delba** [comment]
Hi @all, the project has been updated for Swift 5.1.

Also the error `Function with uninhabited return type 'PermissionType' is missing call to another never-returning function on all paths` has been fixed by adding an (internal) `never` case to `PermissionType`.
