### ISSUE TITLE
Still error on compiling in swift version 4.2

### ISSUE THREAD

**Issue by purva-dev** [delba/Permission#138]
I've installed using _cocoa pods_ -->
**pod 'Permission', :git => 'https://github.com/evdeve/Permission'**

still i m getting below error : 

> **Function with uninhabited return type 'PermissionType' is missing call to another never-returning function on all paths**

**Comment by quido3** [comment]
I have the same problem. Did you find a solution? I have been looking at different forks and all seem to have the same problem.

**Comment by purva-dev** [comment]
> I have the same problem. Did you find a solution? I have been looking at different forks and all seem to have the same problem.

no i didn't find any solution till now

**Comment by khambir** [comment]
try this (Swift 5 version):

`pod 'Permission', :git => 'https://github.com/khambir/Permission'`

**Comment by koust** [comment]
> I have the same problem. Did you find a solution? I have been looking at different forks and all seem to have the same problem.

Hello , @iOSIndianic  @quido3 

I have same problem. But I solved this problem. 

Solution:

First of all , 
you should be open permission.swift file.

View line 136 in permission.swift

**Change**

`public let type: PermissionType`

**To**

```
public let type: PermissionType {
        fatalError()
}

```

**Comment by purva-dev** [comment]
> try this (Swift 5 version):
> 
> `pod 'Permission', :git => 'https://github.com/khambir/Permission'`

it works.. thanks
