### ISSUE TITLE
Support pre-alert

### ISSUE THREAD

**Issue by oferRounds** [delba/Permission#14]
Would be great to support an option to show a pre-alert, when asking for a certain permission for the first time. This is in order not to waste the app's one-time option to present the system alert (as we know that later on, the user will need to put more work to re-enable it, by going to the Settings)

**Comment by delba** [comment]
I'm not sure to understand, sorry.
You mean when first requesting a permission, showing a pre-alert before the system alert?

**Comment by oferRounds** [comment]
Yes, exactly.

**Comment by delba** [comment]
What's the point?

**Comment by oferRounds** [comment]
As I said - not wasting the one-time option, or in other words - use it only when the app is positive the user will allow the permission.

See here: http://techcrunch.com/2014/04/04/the-right-way-to-ask-users-for-ios-permissions/

**Comment by delba** [comment]
Ok, got it thanks.

That's a very good idea indeed! I might add it in a future release and I'll make sure to ping you on this thread.

Thanks!

**Comment by delba** [comment]
@oferRounds I added the support for pre-alert in 1e0e483f11434f28d6c183310675275df922b709

I still have to write the doc and add some instructions in the README before I release a new version though.

Meanwhile I'd be interested by your feedback 😃
