### ISSUE TITLE
Alerts are not showing up in iOS 13

### ISSUE THREAD

**Issue by ZaidPathan** [delba/Permission#142]
Seems issue is here:

`var vc = delegate?.window??.rootViewController`

Window is coming `nil`.
iOS 13 uses SceneDelegate's window.

**Comment by delba** [comment]
Hi @ZaidPathan ! Thanks for the heads up, it has been fixed in the `3.1.2` version.
See https://github.com/delba/Permission/commit/9c729fb89c21a7005c967c9f903a5cc8517887eb
