### ISSUE TITLE
I don't know what happened。。。。。。

### ISSUE THREAD

**Issue by HelloHchen** [delba/Permission#143]
![image](https://user-images.githubusercontent.com/38774301/68757284-aa212e00-0646-11ea-9db1-cd4f9577ea68.png)

![image](https://user-images.githubusercontent.com/38774301/68757361-c8872980-0646-11ea-9ca8-a7a23c575182.png)

**Comment by HelloHchen** [comment]
![image](https://user-images.githubusercontent.com/38774301/68758056-09337280-0648-11ea-8156-d72b15c1b345.png)

**Comment by delba** [comment]
Please read the installation instructions here
https://github.com/delba/Permission/blob/master/README.md

**Comment by HelloHchen** [comment]
![image](https://user-images.githubusercontent.com/38774301/68762938-2bca8900-0652-11ea-9d01-d46d93fe489b.png)

![image](https://user-images.githubusercontent.com/38774301/68763029-6a604380-0652-11ea-9118-cbe904b50aff.png)


Why shut down my issuse? Because you're the author? Has my problem been solved? Isn't that what you wrote on readme?

**Comment by HelloHchen** [comment]
![image](https://user-images.githubusercontent.com/38774301/68764626-03dd2480-0656-11ea-8b76-4caa3c4cfb53.png)

As you can see, I can't access the static properties in your implementation。My Xcode version is 11.2.1

**Comment by delba** [comment]
You might want to read the `PermissionConfiguration.xcconfig` part.
Also your initial screenshot suggested that you didn't read the installation instructions.

**Comment by HelloHchen** [comment]
Yes, so I'm sorry. I think it's very troublesome, so I decided to encapsulate it myself and say sorry again

**Comment by HelloHchen** [comment]
When I see all the issues, I find that I'm not the only one who has the same problem. I use CocoaPods...........
