### ISSUE TITLE
an error when running app

### ISSUE THREAD

**Issue by omidkh68** [delba/Permission#16]
in file "Utitilies.swift"
<img width="818" alt="screen shot 1395-01-27 at 17 49 54" src="https://cloud.githubusercontent.com/assets/4400137/14562520/62f23c24-0332-11e6-9cc9-20becf48e0ef.png">

I have an error when app want to compile for run, xcode get (expected declaration) And (expected initial value after =) error!

can anyone help?

**Comment by delba** [comment]
Hi @omidkh68,

That's not an error from the `Permission` lib.

The `#selector` syntax has been introduced in Swift 2.2, so you might want to update your Swift version or use a previous version of `Permission`.

**Comment by omidkh68** [comment]
@delba thank you so much!
its solved by update my xcode 7,3 and swift 2.2 :)

**Comment by delba** [comment]
Cheers !!

You're welcome :)
