### ISSUE TITLE
Continuous permission status checking

### ISSUE THREAD

**Issue by sunshinejr** [delba/Permission#20]
I would love if there was an option of a continuous checks for specific permission. Like for example, I need to know if user changed the location permission so I can change the UI based off that. Do you think it could be implemented? Thanks! 🐼

**Comment by delba** [comment]
It's interesting but - for now - out of the scope of this lib. Thanks for the suggestion though :)

**Comment by delba** [comment]
Hi @sunshinejr,

I added RxPermission in the README 072d9277b45c2bd9fada5e44280bc9b6f9601d3e

Thank you!
