### ISSUE TITLE
When trying to request permission for notification

### ISSUE THREAD

**Issue by gitton** [delba/Permission#21]
] -[Permission.Permission finishedShowingNotificationPermission]: unrecognized selector sent to instance 0x7fc8daeb2250

**Comment by delba** [comment]
Which version of permission please?

**Comment by delba** [comment]
@gitton I can't reproduce the error you're having. Which version of `Permission` do you use?

**Comment by gitton** [comment]
Thank you for your response i had updated the library and it works fine now 

##

**Comment by delba** [comment]
Ok cool :)
