### ISSUE TITLE
Printing denied without the dialog is being clicked either on Don't allow or ok when asking permission for Notifications

### ISSUE THREAD

**Issue by gitton** [delba/Permission#22]
Printing denied without the dialog is being clicked either on Don't allow or ok

 let permission: Permission = .Notifications(categories: nil)
    permission.request { status in
        switch status {
        case .Authorized:    print("authorized")
        case .Denied:        print("denied")
        case .Disabled:      print("disabled")
        case .NotDetermined: print("not determined")
        }

**Comment by delba** [comment]
> Printing denied without the dialog is being clicked either on Don't allow or ok

What do you mean?

**Comment by gitton** [comment]
it is calling case .Denied when permission.request is called  before the user response (works fine with permission like contacts etc)

**Comment by delba** [comment]
I can't reproduce. Which version are you using?

**Comment by gitton** [comment]
version 1.3

**Comment by delba** [comment]
I still can't reproduce. What's the result of `permission.status` ?

**Comment by gitton** [comment]
NotDetermined

**Comment by delba** [comment]
Mmmm... Sorry but I don't see. Maybe update the lib like you did https://github.com/delba/Permission/issues/21 ?
