### ISSUE TITLE
Crash when changing permissions in iOS Settings app

### ISSUE THREAD

**Issue by mathiasgithub** [delba/Permission#30]
If I set a closure as below, then open the iOS Settings app and change the permission there, the app will crash

`permission.request { status in
    switch status {
    case .Authorized:    print("authorized")
    case .Denied:        print("denied")
    case .Disabled:      print("disabled")
    case .NotDetermined: print("not determined")
    }
}`

**Comment by delba** [comment]
You have to use a real device, not the simulator for this :/

https://developer.apple.com/library/ios/documentation/IDEs/Conceptual/iOS_Simulator_Guide/TestingontheiOSSimulator/TestingontheiOSSimulator.html

**Comment by mathiasgithub** [comment]
I did get this crash on both the simulator and testing on device

**Comment by delba** [comment]
After install the app on a device, click "Stop the running scheme or application" in Xcode and then reopen your app. Unfortunately, you won't have access to the log messages...

**Comment by mathiasgithub** [comment]
Got it. Thanks a lot!

**Comment by KittenYang** [comment]
@mathiasgithub @delba  Still crash, I am doubtful that it's the iOS bug.

**Comment by cooliopas** [comment]
@KittenYang is right. Its crashing on device, even stopping the app on Xcode and reopening.

**Comment by cooliopas** [comment]
This is what I get on device logs:

Quitting application (APP BUNDLE ID HERE) in response to privacy settings change

Its not a crash, but a SIGKILL

Its not "Permission" fault at all.
