### ISSUE TITLE
Notifications are considered Denied even if just one type is denied

### ISSUE THREAD

**Issue by DimDL** [delba/Permission#35]
When requesting Notification Permissions, it is fairly common to prompt user for all 3 types (badge, sound, alert), but consider notifications 'on' even if user turned off says sound or badge. Currently .status() will return .Denied/.NotDetermined in the second case.

Suggestions:
1) Either change this policy, ie. 

```
    var statusNotifications: PermissionStatus {
        guard case .Notifications(let settings) = type else { fatalError() }

        if let types = Application.currentUserNotificationSettings()?.types where types.rawValue > 0 {
            return .Authorized
        }

        return Defaults.requestedNotifications ? .Denied : .NotDetermined
    }
```

2) Or let users decide, either by letting them specify a 'validationBlock', or by returning them the activated types. For example, one can add associated value to the PermissionStatus enum:

```
public enum PermissionStatus {
    case Authorized(UIUserNotificationType)
    case Denied
    case Disabled
    case NotDetermined
}
```

FYI, my wrapper workaround :

```
// Permissions created with all 3 types, but perm = Permission.Notifications(types:[.Badge, .Sound, .Alert], categories:nil)

 class func permissionStatus() -> PermissionStatus {
        // Permission considère qu'on est 'Denied' si on a pas 100% des types demandés; nous on considère que si on a au moins 1 c'est suffisant (ex: seul .Badge activé alors qu'on a demandé badge, Sound, Alert)
        let buggyStatus = perm.status
        if buggyStatus == .Denied {
            let acceptance = Int(UIApplication.sharedApplication().currentUserNotificationSettings()?.types.rawValue ?? 0
            return acceptance > 0 ? .Authorized : .Denied
        }
        return buggyStatus
    }

```

**Comment by delba** [comment]
> let buggyStatus = perm.status

So much dis in your variable names 😂 

I agree that the default behavior should be to return `.Authorized` whatever the notification type.
What do you suggest to handle the "strict" (`.Authorized` if the permitted notifications types strictly match the ones requested) case ?

**Comment by AndrewSB** [comment]
I like

``` swift
protocol AuthorizedType {
    var isMostAuthorizedState: Bool { get }
}

extension UIUserNotificationType: AuthorizedType {
    var isMostAuthorizedState: Bool {
         return self == .alert // does everyone agree that alert is the highest level of permission?
    }
}

public enum PermissionStatus {
    case Authorized(AuthorizedType?)
    case Denied
    case Disabled
    case NotDetermined
}
```

`AuthorizedType` is basically just a marker protocol, with a helpful flag letting you know if your user has allowed the maximum level of permission. Anything else can be added to it 😄

**Comment by delba** [comment]
The new behavior is to return `authorized` if at least one notification type is granted.
