### ISSUE TITLE
Pre-permission not working with .Bluetooth

### ISSUE THREAD

**Issue by jakerockland** [delba/Permission#36]
I'm having an issue using the pre-permission with the .Bluetooth Permission type. Does this have something to do with this line in Permission.swift `case .Bluetooth:         requestBluetooth(self.callback)`?

Still a bit new to Swift so not 100% sure what is wrong here.

**Comment by delba** [comment]
What issue do you have?

**Comment by jakerockland** [comment]
The pre-permission seems to always fire, even if the permission has already been authorized previously, is this correct behaviour? Perhaps I'm just a bit confused about the expected behaviour.

**Comment by delba** [comment]
It definitely shouldn't fire indeed.
I'm gonna look into it

**Comment by jakerockland** [comment]
That would be awesome, thanks so much for looking into it. If you have any issue re-creating the error I can try to send you some sample code of exactly how I am implementing the framework, but my implementation was pretty much just based on the sample documentation you gave but using the .Bluetooth permission.

**Comment by AndrewSB** [comment]
@delba: Im seeing this too.

**Comment by jakerockland** [comment]
@AndrewSB I believe I found a fix to this if you check out #70. 😄

**Comment by delba** [comment]
@AndrewSB did you had a change to try #70 ? I'm going to test it as well on my side :)

**Comment by AndrewSB** [comment]
I'll test #70 later today!

**Comment by jakerockland** [comment]
This is now replaced with #74 for isolation from #69 @delba @AndrewSB

**Comment by jakerockland** [comment]
#74 has now been replaced with #76 😛 @AndrewSB

**Comment by delba** [comment]
Fixed in https://github.com/delba/Permission/commit/f6b36cebcc72f2f99148b05cc813774d9a87972b
