### ISSUE TITLE
Add complete example

### ISSUE THREAD

**Issue by firefoxNX** [delba/Permission#4]
I see the animated gif has a view asking for different permissions. Can that be made available to see how  to add Permission API?

**Comment by delba** [comment]
Hi @firefoxNX 

I updated the [example code](https://github.com/delba/Permission#example) in d18816b7a25d533e7c10db912205ad3e5976758a 
But unfortunately I deleted the example app after creating the GIF :/

Let me know if it helps!

**Comment by icanswiftabit** [comment]
Is it only my or ,according to your example, buttons added to view are with frame(0.0, 0.0, 0.0, 0.0). I'm trying on blank one view app.

**Comment by delba** [comment]
Yes I set the frame, font etc in the `// ...` part of the example because otherwise it would have only added noise.

**Comment by icanswiftabit** [comment]
Oh.. Got it. Thanks for clarification.

**Comment by icanswiftabit** [comment]
But again what's the point of using `setTitles` if there isn't default font, frame etc?

**Comment by delba** [comment]
Please see the setTitle method of UIButton

**Comment by icanswiftabit** [comment]
@delba so I've done it like in your example, I've also used autolayout to setFrame. But I don't understand why title is not changing after I allow or deny resource.

[code](https://gist.github.com/Dudi00/69a5996f380b187c6c8f5e1e84c30458)

**Comment by firefoxNX** [comment]
@Dudi00 can you please share fully working example? That would be awesome!

**Comment by icanswiftabit** [comment]
@firefoxNX I will as soon as I make it to work like on gif.

**Comment by icanswiftabit** [comment]
@firefoxNX If you want in my fork there is example app

**Comment by firefoxNX** [comment]
Awesome @Dudi00 Thanks!
