### ISSUE TITLE
Fix CFBundleIdentifier Swift 3

### ISSUE THREAD

**Issue by AdiAyyakad** [delba/Permission#55]
I tried running my program with Permission, and I manually edited the files to have the #54 issue be resolved. This resulted in it claiming that the CFBundleIdentifier wasn't in the Info.plist.

**Comment by delba** [comment]
Hi @njaditya, please check out the latests update on the [`swift-3.0` branch](https://github.com/delba/Permission/tree/swift-3.0) and let me know if you still encounter this issue :)

**Comment by AdiAyyakad** [comment]
Hey, thank you so much it seems to have been fixed!
