### ISSUE TITLE
This app attempts to access privacy-sensitive data without

### ISSUE THREAD

**Issue by jonandersen** [delba/Permission#57]
When submitting the app with Xcode 8 i get an error requesting me to add keys to the .plist. Not sure what the best course of action is here. I could work around it for now by deleting the files I didn't need as adding all the keys seems like a ground for rejection. M aybe there's an option to separate them into different modules?

> Dear developer,
> 
> We have discovered one or more issues with your recent delivery for "app-name". To process your ? delivery, the following issues must be corrected:
> 
> This app attempts to access privacy-sensitive data without a usage description. The app's Info.plist must contain an NSContactsUsageDescription key with a string value explaining to the user how the app uses this data.
> 
> This app attempts to access privacy-sensitive data without a usage description. The app's Info.plist must contain an NSCalendarsUsageDescription key with a string value explaining to the user how the app uses this data.
> 
> This app attempts to access privacy-sensitive data without a usage description. The app's Info.plist must contain an NSBluetoothPeripheralUsageDescription key with a string value explaining to the user how the app uses this data.
> 
> This app attempts to access privacy-sensitive data without a usage description. The app's Info.plist must contain an NSMicrophoneUsageDescription key with a string value explaining to the user how the app uses this data.
> 
> This app attempts to access privacy-sensitive data without a usage description. The app's Info.plist must contain an NSMotionUsageDescription key with a string value explaining to the user how the app uses this data.
> 
> Once these issues have been corrected, you can then redeliver the corrected binary.
> 
> Regards,
> 
> The App Store team

**Comment by timlehr** [comment]
Yeah that new policy kind of breaks this library. You could split it up in different modules, but that would be quite the hassle to integrate into projects.

**Comment by KelvinJin** [comment]
😞 This is really sad. Apple is trying to make things harder.

**Comment by rlaferla** [comment]
PermissionScope also has this problem.  I was looking for a project that addressed it.  Sadly, Apple comes up with lots of restrictions and yet has no API to address it.  Since nearly every app requires some sort of permission, they should provide a better API as well as a better user interface for permissions.  What the have now is inadequate.

**Comment by hartbit** [comment]
@timlehr I don't think it would be such a hassle. Simply `pod 'Permission/Notification'` and all other modules you require. I wouldn't mind helping out on the migration.

**Comment by jakerockland** [comment]
@hartbit @delba would also be happy to help in the migration if there is a plan to modularize things.

**Comment by justinmakaila** [comment]
Would love some sort of update on this. I literally use the library to manage Notification permissions via Carthage, and just received this email on my latest app submission. I'm thinking the workaround is to come up with defaults, but seeing as I don't request them, I'm afraid of further rejection.

**Comment by shagedorn** [comment]
We addressed the issue in our library by hiding all permissions behind build flags, so code that is not used will never ship. It does require users of the library to place an `xcconfig` file in a pre-defined location. CocoaPods users can just specify the sub specs they need without any further configuration:

https://github.com/iosphere/ISHPermissionKit

**Comment by AndrewSB** [comment]
@shagedorn do you know if it's possible to do that with Carthage?

**Comment by justinmakaila** [comment]
@AndrewSB Carthage just builds the shared schemes in your project. I think if there was a scheme to load from a configuration similarly to CocoaPods uses configurations, it could be done.

_EDIT_: They provide an example in [this section](https://github.com/iosphere/ISHPermissionKit#dynamically-linked-framework)

**Comment by AndrewSB** [comment]
That sounds doable @justinmakalia.
I'm (not) looking forward to splitting my permission library into 9 (or is it more?) framework targets 😔

Happy to help with the migration as well, though

**Comment by justinmakaila** [comment]
@AndrewSB Not really sure how best to handle the enumerations if we're hiding them behind flags, using

```
open var status: PermissionStatus {
  switch type {
    #ifdef CONTACTS_PERMISSION_ENABLED
      case .contacts:          return statusContacts
    #endif
    ...
  }
}
```

is the best way to go about it

**Comment by AndrewSB** [comment]
@justinmakaila not sure I understand what you said. Are you saying that ⬆️ **is** or **isn't** the best way to go about the migration?

**Comment by justinmakaila** [comment]
Started work on https://github.com/delba/Permission/pull/75.

Lemme know what you guys think

**Comment by delba** [comment]
The Swift 3.0 is _finally_ out for Carthage:

```
github "delba/Permission" >= 2.0
```

There still is some work to do for CocoaPods (creating the subpod etc.) :/
If someone feels like submitting a PR for that, it would be wonderful 😃 

Thanks to all the contributors 🎉

**Comment by rsaarloos** [comment]
I create a PR for the CocoaPods part in #78. @delba can you have a look and tell me what you think

**Comment by delba** [comment]
Hey everyone, the `Permission` pods are here:

```
use_frameworks!

pod 'Permission/Camera'
pod 'Permission/Notifications'
```

Again, to all the contributors, **thank you**.

I guess it's time to close this issue now 😅
