### ISSUE TITLE
Swift 3 Support?

### ISSUE THREAD

**Issue by learnwithgabbar** [delba/Permission#58]

**Comment by gautier-gdx** [comment]
techmehra there is a swift-3.0 branch, if you re using carthage for example, 
add: github "delba/Permission" "swift-3.0" in your cartFile and you're ready to go, hopefully it will be merged soon in the master branch

**Comment by jakerockland** [comment]
@gautier-gdx hoping this gets merged to master soon as well, any update @delba ?

**Comment by delba** [comment]
I'm closing this one, please see #60 :)
