### ISSUE TITLE
app crash on launch(swift 3)

### ISSUE THREAD

**Issue by alexkotenko** [delba/Permission#59]
Hello
I use the branch swift-3.0 and xcode Version 8.0. I run the application on ios 10 and everything works. 
But if I run the application on ios 9 , app crash on launch and I get error 
dyld: Library not loaded: /System/Library/Frameworks/Speech.framework/Speech
 Referenced from: /private/var/containers/Bundle/Application/XXXXXXXX/Frameworks/Permission.framework/Permission
 Reason: image not found
Thanks

**Comment by learnwithgabbar** [comment]
same here , In one of our development device , But in other devices this is working fine please help

**Comment by zxy198717** [comment]
Same issue on iPhone 6s plus, Please help.

**Comment by learnwithgabbar** [comment]
Remove this library through cocoapods and add manually than the error will fixed

**Comment by kiokumicu** [comment]
same error

**Comment by sgerardi** [comment]
The project needs to be updated to include "s.weak_framework = 'Speech'" in the pod spec

A short term fix would be to add the Speech.framework manually to the Permission target in the Pods project.  However you will need to manually add it back after every 'pod install/update'

**Comment by olferuk** [comment]
Same here, the workaround from mr. @sgerardi didn't help 😞

**Comment by kiokumicu** [comment]
@sgerardi thx, it's work
@EnlightenedCSF I create PR https://github.com/delba/Permission/pull/63

**Comment by delba** [comment]
Hi @alexkotenko, thanks for the issue!

The issue has been fixed in #63 :)
