### ISSUE TITLE
Swift 3.0 release

### ISSUE THREAD

**Issue by sunshinejr** [delba/Permission#60]
Hey Damien! I don't know the current state of this library for Swift 3.0, but would it be possible to release alpha/beta version if it is not completed yet? Would love to update [RxPermission](https://github.com/sunshinejr/RxPermission) to the newest standards 🐼 Cheers!

**Comment by hernangonzalez** [comment]
+1, I've been using branch `swift-3.0`

**Comment by eikebartels** [comment]
I guess its time for a merge of https://github.com/delba/Permission/tree/swift-3.0 ?

**Comment by jakerockland** [comment]
Given XCode 8 being out of beta now, I think it would make sense to merge swift-3.0 to master. @delba ?

**Comment by rsaarloos** [comment]
+1

**Comment by delba** [comment]
Sorry everyone, I was a bit busy lately...
I will merge `swift-3.0` into `master` (and most importantly release a new version) as soon as I tackle  some of the remaining issues (by this week-end I hope)

**Comment by jakerockland** [comment]
@delba No need for apologies, sounds good to me! 😄

**Comment by mingmingsuper** [comment]
Hi, delba When would you merge swift-3.0 into master? I need your help!!!

**Comment by delba** [comment]
@mingmingsuper It's coming very soon!
Check @justinmakaila PR here https://github.com/delba/Permission/pull/75 😉

**Comment by mingmingsuper** [comment]
@delba Thanks!

**Comment by JeffESchmitz** [comment]
My vote of a merge swift-3.0 into master. Would like to use in a new project that is starting this week (Nov 1. 2016).

Thanks for the excellent work!

**Comment by delba** [comment]
The `swift-3.0` branch is now `master`. You can find the version compatible with Swift 2.2 on the `swift-2.2` branch.

I would be awesome to get some feedback on the [compilation conditions](https://github.com/delba/Permission#configuration) (kudos to @justinmakaila) before shipping a proper release.

Thanks!

**Comment by mingmingsuper** [comment]
Hi @delba the sources update complete but the podspec file not update the version is also 1.5,please update it,Thanks!

**Comment by mingmingsuper** [comment]
How to config PermissionConfiguration.xcconfig correct?

**Comment by delba** [comment]
Thanks to all the contributors, the Swift 3.0 version is finally out 🎉

```
github "delba/Permission" >= 2.0
```

The CocoaPod isn't here yet... More info here #57

**Comment by loverde-co** [comment]
Swift 3.0 is there on CocoaPods ?
