### ISSUE TITLE
Retain cycle with the PermissionSet delegate property

### ISSUE THREAD

**Issue by yannickl** [delba/Permission#65]
I've tried the new memory graph tool with Xcode 8 and your swift3 branch and there is a retain cycle with the delegate property of the `PermissionSet` object:

<img width="248" alt="screen shot 2016-10-13 at 21 33 40" src="https://cloud.githubusercontent.com/assets/798235/19364055/ebb71a14-918c-11e6-9f0d-0a10997d4011.png">

To avoid this issue, you should declare the delegate as `weak`. I'll make a PR.

**Comment by delba** [comment]
All of your 3 (three!) PRs have been merged 🎉 

Thanks @yannickl, it's very appreciated :)
