### ISSUE TITLE
Need help configuring

### ISSUE THREAD

**Issue by LarsWith** [delba/Permission#77]
<img width="258" alt="conf" src="https://cloud.githubusercontent.com/assets/22659171/20009592/5f23f20a-a2a5-11e6-9b82-76404cc8b9a3.png">

Should I copy paste that file into the root of my project then add the following?:

```
PERMISSION_ADDRESS_BOOK      = // PERMISSION_ADDRESS_BOOK
PERMISSION_BLUETOOTH         = // PERMISSION_BLUETOOTH
PERMISSION_CAMERA            = PERMISSION_CAMERA
PERMISSION_CONTACTS          = // PERMISSION_CONTACTS
PERMISSION_EVENTS            = // PERMISSION_EVENTS
PERMISSION_LOCATION          = // PERMISSION_LOCATION
PERMISSION_MICROPHONE        = // PERMISSION_MICROPHONE
PERMISSION_MOTION            = // PERMISSION_MOTION
PERMISSION_NOTIFICATIONS     = PERMISSION_NOTIFICATION
PERMISSION_PHOTOS            = // PERMISSION_PHOTOS
PERMISSION_REMINDERS         = // PERMISSION_REMINDERS
PERMISSION_SPEECH_RECOGNIZER = // PERMISSION_SPEECH_RECOGNIZER
PERMISSION_MEDIA_LIBRARY     = // PERMISSION_MEDIA_LIBRARY

// Do not modify this line. Instead, remove comments above as needed to enable the categories your app uses.
PERMISSION_FLAGS= $(PERMISSION_ADDRESS_BOOK) $(PERMISSION_BLUETOOTH) $(PERMISSION_CAMERA) $(PERMISSION_CONTACTS) $(PERMISSION_EVENTS) $(PERMISSION_LOCATION) $(PERMISSION_MICROPHONE) $(PERMISSION_MOTION) $(PERMISSION_NOTIFICATIONS) $(PERMISSION_PHOTOS) $(PERMISSION_REMINDERS) $(PERMISSION_SPEECH_RECOGNIZER) $(PERMISSION_MEDIA_LIBRARY)

SWIFT_ACTIVE_COMPILATION_CONDITIONS = $(inherited) $(PERMISSION_FLAGS)
```

Right now that file looks like this:

```
CONFIGURATION_BUILD_DIR = $PODS_CONFIGURATION_BUILD_DIR/Permission
GCC_PREPROCESSOR_DEFINITIONS = $(inherited) COCOAPODS=1
HEADER_SEARCH_PATHS = "${PODS_ROOT}/Headers/Private" "${PODS_ROOT}/Headers/Public"
OTHER_SWIFT_FLAGS = $(inherited) "-D" "COCOAPODS"
PODS_BUILD_DIR = $BUILD_DIR
PODS_CONFIGURATION_BUILD_DIR = $PODS_BUILD_DIR/$(CONFIGURATION)$(EFFECTIVE_PLATFORM_NAME)
PODS_ROOT = ${SRCROOT}
PRODUCT_BUNDLE_IDENTIFIER = org.cocoapods.${PRODUCT_NAME:rfc1034identifier}
SKIP_INSTALL = YES
```

Thanks in advance!

**Comment by mingmingsuper** [comment]
When I updated pod,I need to Re Config the config file to project,If I don't Re config the config file,the project can't run,the error is .camera or .photos can't find!

**Comment by delba** [comment]
You can't configure Permission when using CocoaPods yet. The configuration section on the README only applies for Carthage.

**Comment by mingmingsuper** [comment]
@delba How can I use PermissionFlags.xcconfig in my project? If I not config it in my project,my project can't run,it has some errors appear! I need your help!!

**Comment by mingmingsuper** [comment]
May I have your email?I want to send mail to you with some pictures,thanks!

**Comment by delba** [comment]
Could you be more specific please ? What issues are you having when following the [instructions](https://github.com/delba/Permission#configuration) ?

**Comment by mingmingsuper** [comment]
Sorry my English is poor,I don't known how to use PermissionConfiguration.xcconfig to config in my project,so I need your help,Thanks!

**Comment by mingmingsuper** [comment]
I need a full demo,Thanks!My email is mingmingsuper@gmail.com,If you can make a demo project to me,please send it to my email,thanks!

**Comment by delba** [comment]
Sorry, it is too much work to provide individual support with a full demo for each and everyone.
If you have a specific issue when following the instructions, I'm offering to help though.

**Comment by mingmingsuper** [comment]
I following the instructions,But I don't understand how to config the file PermissionConfiguration.xcconfig.

<img width="521" alt="ccf7f5b7-c53c-4824-875e-cba99b7c3a1a" src="https://cloud.githubusercontent.com/assets/4538635/20052890/f3556fa4-a510-11e6-8b9c-974be2e63044.png">
I must re config it like config on that picture when I update pod?

**Comment by delba** [comment]
> You can't configure Permission when using CocoaPods yet. The configuration section on the README only applies for Carthage.

**Comment by mingmingsuper** [comment]
If I don't config it ,my project comes some errors like the picture below
![qq20161107-0](https://cloud.githubusercontent.com/assets/4538635/20053002/862f9250-a511-11e6-84a6-3985997d5992.png)

**Comment by mingmingsuper** [comment]
Can't find photos,camera and other enums in PermissionType!

**Comment by mingmingsuper** [comment]
Now I use swift 3.0+
