### ISSUE TITLE
DisabledAlert and DeniedAlert fail to show with warning: Warning: Attempt to present on whose view is not in the window hierarchy!

### ISSUE THREAD

**Issue by DimDL** [delba/Permission#8]
DisabledAlert and DeniedAlert fail to show when there is a presented VC displayed (aka modal VC).

Console : `Warning: Attempt to present on whose view is not in the window hierarchy!`

When presenting an alert, we need to test for rootVC.presentedViewControllerC, and fallback to rootVC if needed

I've created a pull request: https://github.com/delba/Permission/pull/7

**Comment by delba** [comment]
Fixed by #7

Thanks again :)
