### ISSUE TITLE
pod 'Permission/Camera' not found.

### ISSUE THREAD

**Issue by arpitdongre** [delba/Permission#81]
[!] Unable to satisfy the following requirements:

- `Permission/Camera` required by `Podfile`

None of your spec sources contain a spec satisfying the dependency: `Permission/Camera`.

You have either:
 * out-of-date source repos which you can update with `pod repo update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.

**Comment by ArpitOnTheWay** [comment]
Solved it by running `pod repo update`.

**Comment by arpitdongre** [comment]
Solved it by running `pod repo update`
