### ISSUE TITLE
Action styles for confirm/settings and cancel are flipped

### ISSUE THREAD

**Issue by jakerockland** [delba/Permission#82]
It looks like the action styles for the confirm and settings actions are flipped with the cancel action based on Apple's convention. Making a minor PR that fixes this.

**Comment by jakerockland** [comment]
Relevant: http://www.openradar.me/radar?id=5490788398006272

**Comment by jakerockland** [comment]
@delba Is it possible to merge the fix to this at #83 soon? 😄

**Comment by delba** [comment]
Fixed by #83

**Comment by jakerockland** [comment]
Hey @delba, is it possible to increment the release number to v2.0.2 so that these changes are incorporated for Carthage?

**Comment by delba** [comment]
Hey @jakerockland, I just released v2.0.2 .
Thanks for reminding me ;)

**Comment by jakerockland** [comment]
No prob, thank you @delba ! 😄
