### ISSUE TITLE
Use without Carthage or Cocoapods -> error: Type 'Permission' has no member 'locationWhenInUse'

### ISSUE THREAD

**Issue by dillidon** [delba/Permission#85]
how can I solve that?

I copied all files as well as .xcconfig to project's root dir... Till update to Swift 3.0 everything was working

**Comment by jessetipton** [comment]
I just started seeing this as well after switching from Carthage to CocoaPods (But for `notifications`, not `locationWhenInUse`).

**Comment by delba** [comment]
@dillidon You have to set the `.xcconfig` file as a configuration file in your project configurations. You might want to use Carthage though, it will make it so much easier :)

@jessetipton There is no need of using PermissionConfiguration.xcconfig with CocoaPods.
See the instructions [here](https://github.com/delba/Permission#cocoapods).
