### ISSUE TITLE
Support acquire network permission

### ISSUE THREAD

**Issue by cybertk** [delba/Permission#86]
As iOS 10 add new permission of **Wireless Data**, it's better if **Permission** supports it.

The **Wireless Data** can be also accessed in **Settings.app -> Cellular -> App using WLAN && Cellular**

**Comment by delba** [comment]
Hi @cybertk, it seems that this permission can't be requested from an app (?)
Please correct me if I'm wrong

**Comment by cybertk** [comment]
The permission dialog is presented by System. But AFAK the dialog is triggered by calling a network API, such as `NSURLSession`
