### ISSUE TITLE
Is there any support for localization?

### ISSUE THREAD

**Issue by groue** [delba/Permission#87]
Maybe I missed it?

**Comment by groue** [comment]
For whoever is interested in localizing this library, you can find the beginning of a French translation here: https://github.com/pierlis/Permission.

**Comment by ysoftware** [comment]
Partially translated to russian using pierlis/Permission implementation in here: https://github.com/ysoftware/Permission

**Comment by delba** [comment]
Hi @groue and @ysoftware, I'd love to add it to the lib 😍 

Would you mind creating a PR, please ?

[I'm closing this issue]

BTW @groue, I think we met at the 2016 FrenchKit..

**Comment by groue** [comment]
@delba Yes, I was there. But you didn't look like a fox, then ;-)
