### ISSUE TITLE
setTitles doesn't work 

### ISSUE THREAD

**Issue by ysoftware** [delba/Permission#88]
**Class PermissionButton**

I'm not sure what's going on, but in
`func setTitles(_ titles: [PermissionStatus: String?], forState state: UIControlState = UIControlState())` the first line is 
`guard [.highlighted].contains(state) else { return }` 
which means, with the default value of `state` you've specified, this function will never run.
Same goes for a few other functions. 

I tried to set up my buttons just like in readme and their title is always empty.

**Comment by ysoftware** [comment]
It also seems, you can't set multiple titles for `.normal` state.
I'm not sure what that guard check was supposed to do, but removing it in my fork solved my problem.

**Comment by delba** [comment]
Hey @ysoftware, thanks for the issue.

That's definitely a bug that was introduced during the automatic transition to Swift 3 (https://github.com/delba/Permission/commit/1ef678af334e71c982b476ba344b1a9194c49f8e) and has been fixed here https://github.com/delba/Permission/commit/37c27702d522ff7da6a90e6f27964f693ce1e076.

> It also seems, you can't set multiple titles for .normal state.

I'm not sure what you mean (?)

The `guard` is preventing the user to set titles for states other than `.normal` or `.highlighted`. It might be removed completely in the upcoming version of the lib.

Thanks again!

**Comment by ysoftware** [comment]
> I'm not sure what you mean (?)

Since it's only checking for [.highlighted] and not .normal.
 
Anyway, Thanks for the responce.
