### ISSUE TITLE
No option to update state of PermissionButton on applicationWillEnterForeground

### ISSUE THREAD

**Issue by Jeehut** [delba/Permission#93]
I've got a PermissionButton in my app, and although I know it is specified that the app will crash when changing permissions, it doesn't seem to crash when changing the `location services` permission (whenInUse) in my tests – neither in the Simulator, nor on the Device (both on debug and release builds) using iOS 10.2.1.

So, I need to be able to trigger an update of the PermissionButtons state manually in my app like so:

```swift
func applicationWillEnterForeground(_ application: UIApplication) {
    // some code to get the permission button
    permissionButton.update() // calls the render() method internally
}
```

**Comment by delba** [comment]
Let's keep the discussion in #94 !
Thanks for the PR btw :)
