### ISSUE TITLE
Not compatible with Xcode 8.3 beta3

### ISSUE THREAD

**Issue by chenyunguiMilook** [delba/Permission#95]
<img width="963" alt="2017-02-21 12 02 17" src="https://cloud.githubusercontent.com/assets/11513291/23150353/d8927a2a-f82d-11e6-9280-10315c0abf9f.png">

**Comment by LLIo6oH** [comment]
Same truble

**Comment by delba** [comment]
Thanks for the issue @chenyunguiMilook, I'll make sure to update the lib when Xcode 8.3 is released.

**Comment by Dschee** [comment]
Xcode 8.3 is released now, could we reopen this and fix the issue? Thanks!

**Comment by delba** [comment]
https://github.com/delba/Permission/pull/101
